### ISSUE TITLE
Failed with error: Error: "NotFound" (12) reason: "(null)" num: (0)

### ISSUE THREAD

**Issue by yjhjstz** [indutny/core2dump#8]
> Failed with error: Error: "NotFound" (12) reason: "(null)" num: (0)

mac platform, core generate by sending SIGSEGV.

and meet this:
> [root@centos7-x64 node]# ../core2dump/core2dump -c  core.13555 -o ./heap1
Constant: ConsStringTag was not found
Constant: ExternalStringTag was not found
Constant: FirstNonstringType was not found
Constant: HeapObjectTag was not found
Constant: HeapObjectTagMask was not found
Constant: IsNotStringMask was not found
Constant: NotStringTag was not found
Constant: PointerSizeLog2 was not found
Constant: SeqStringTag was not found
Constant: ConsStringTag was not found

**Comment by indutny** [comment]
I think you may want to supply the binary to it, using `-b` CLI option.

**Comment by yjhjstz** [comment]
> ➜  core2dump git:(master) ✗ build/Debug/core2dump -b ../iojs/node -c /cores/core.12919 -o ./heapdump 
Failed with error:
Error: "NotFound" (12) reason: "(null)" num: (0)

**Comment by indutny** [comment]
Which node.js version are you trying to run this on?

**Comment by yjhjstz** [comment]
I loved this by generate a new core file. thanks!
