### ISSUE TITLE
builds on unsupported platforms, but always aborts without explanation

### ISSUE THREAD

**Issue by davepacheco** [indutny/core2dump#9]
I built core2dump on illumos, but it just dumps core itself.  This block in cli.c is kind of a trap for unsupported platforms:

https://github.com/indutny/core2dump/blob/40d00671244bc35ed4579124f8c4d830ae1f6102/src/cli.c#L169-L175

I don't assume the tool will necessarily work on unsupported platforms, of course, but in this case, the code already detects that the platform is not supported.  Could this be changed to an `#error` directive so that the build fails?  Right now, it produces a binary that's effectively hardcoded to dump core without any error message.

**Comment by indutny** [comment]
Fixed, but I believe it can possibly work on Illumos, though.

**Comment by davepacheco** [comment]
Thanks!

I hope so as well.  I understood from @rmustacc that the ELF notes representing threads are different from the other systems, but I expect much of the rest may work.

**Comment by indutny** [comment]
Aaah... So it is probably a matter of patching the structure then. Thanks!
